import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { Cron, CronExpression } from '@nestjs/schedule';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository, Between } from 'typeorm';
import { OperationReport, ReportPeriod } from './entities/operation-report.entity';
import { PaginationDto } from '../common/dto/pagination.dto';
import { User } from '../users/entities/user.entity';
import { Contest } from '../contests/entities/contest.entity';
import { Problem } from '../problems/entities/problem.entity';
import { Submission, SubmissionStatus } from '../submissions/entities/submission.entity';
import { Registration } from '../registrations/entities/registration.entity';
import { AntiCheatRecord } from '../anti-cheat/entities/anti-cheat-record.entity';
import { Certificate } from '../certificates/entities/certificate.entity';

@Injectable()
export class ReportsService {
  private readonly logger = new Logger(ReportsService.name);

  constructor(
    @InjectRepository(OperationReport)
    private reportsRepository: Repository<OperationReport>,
    @InjectRepository(User)
    private usersRepository: Repository<User>,
    @InjectRepository(Contest)
    private contestsRepository: Repository<Contest>,
    @InjectRepository(Problem)
    private problemsRepository: Repository<Problem>,
    @InjectRepository(Submission)
    private submissionsRepository: Repository<Submission>,
    @InjectRepository(Registration)
    private registrationsRepository: Repository<Registration>,
    @InjectRepository(AntiCheatRecord)
    private antiCheatRepository: Repository<AntiCheatRecord>,
    @InjectRepository(Certificate)
    private certificatesRepository: Repository<Certificate>,
  ) {}

  @Cron(CronExpression.MONTHLY, {
    name: 'generate_monthly_report',
    timeZone: 'Asia/Shanghai',
  })
  async handleMonthlyReport() {
    this.logger.log('开始生成月度运营报表...');
    try {
      const now = new Date();
      const periodStart = new Date(now.getFullYear(), now.getMonth() - 1, 1);
      const periodEnd = new Date(now.getFullYear(), now.getMonth(), 0);

      await this.generateReport(ReportPeriod.MONTHLY, periodStart, periodEnd, true);
      this.logger.log('月度运营报表生成完成');
    } catch (error) {
      this.logger.error(`月度报表生成失败: ${error.message}`, error.stack);
    }
  }

  async generateReport(
    period: ReportPeriod,
    periodStart: Date,
    periodEnd: Date,
    isAutoGenerated: boolean = false,
  ): Promise<OperationReport> {
    const startOfDay = new Date(periodStart);
    startOfDay.setHours(0, 0, 0, 0);
    const endOfDay = new Date(periodEnd);
    endOfDay.setHours(23, 59, 59, 999);

    const totalUsers = await this.usersRepository.count();
    const newUsers = await this.usersRepository.count({
      where: { createdAt: Between(startOfDay, endOfDay) },
    });

    const totalContests = await this.contestsRepository.count();
    const newContests = await this.contestsRepository.count({
      where: { createdAt: Between(startOfDay, endOfDay) },
    });
    const ongoingContests = await this.contestsRepository.count({
      where: { status: 'ongoing' as any },
    });

    const totalProblems = await this.problemsRepository.count();
    const newProblems = await this.problemsRepository.count({
      where: { createdAt: Between(startOfDay, endOfDay) },
    });

    const totalSubmissions = await this.submissionsRepository.count();
    const newSubmissions = await this.submissionsRepository.count({
      where: { createdAt: Between(startOfDay, endOfDay) },
    });
    const acceptedSubmissions = await this.submissionsRepository.count({
      where: {
        createdAt: Between(startOfDay, endOfDay),
        status: SubmissionStatus.ACCEPTED,
      },
    });
    const averageAcceptanceRate =
      newSubmissions > 0 ? (acceptedSubmissions / newSubmissions) * 100 : 0;

    const registrations = await this.registrationsRepository.count({
      where: { createdAt: Between(startOfDay, endOfDay) },
    });

    const antiCheatAlerts = await this.antiCheatRepository.count({
      where: { createdAt: Between(startOfDay, endOfDay) },
    });

    const certificatesIssued = await this.certificatesRepository.count({
      where: { createdAt: Between(startOfDay, endOfDay) },
    });

    const activeUsers = await this.submissionsRepository
      .createQueryBuilder('submission')
      .select('COUNT(DISTINCT submission.userId)', 'count')
      .where('submission.createdAt BETWEEN :start AND :end', { start: startOfDay, end: endOfDay })
      .getRawOne()
      .then((r) => parseInt(r.count, 10) || 0);

    const periodNames = {
      [ReportPeriod.DAILY]: '日',
      [ReportPeriod.WEEKLY]: '周',
      [ReportPeriod.MONTHLY]: '月',
    };

    const report = this.reportsRepository.create({
      period,
      periodStart,
      periodEnd,
      title: `${periodStart.getFullYear()}年${periodStart.getMonth() + 1}月运营${periodNames[period]}度报表`,
      newUsers,
      activeUsers,
      totalUsers,
      newContests,
      ongoingContests,
      totalContests,
      newProblems,
      totalProblems,
      newSubmissions,
      totalSubmissions,
      acceptedSubmissions,
      averageAcceptanceRate,
      registrations,
      antiCheatAlerts,
      certificatesIssued,
      isAutoGenerated,
    });

    return this.reportsRepository.save(report);
  }

  async findAll(paginationDto: PaginationDto, filters?: {
    period?: ReportPeriod;
  }) {
    const { page, pageSize, sortBy, sortOrder } = paginationDto;
    const skip = (page - 1) * pageSize;

    const queryBuilder = this.reportsRepository.createQueryBuilder('report');

    if (filters?.period) {
      queryBuilder.andWhere('report.period = :period', { period: filters.period });
    }

    queryBuilder.skip(skip).take(pageSize);
    queryBuilder.orderBy(sortBy ? `report.${sortBy}` : 'report.createdAt', sortOrder || 'DESC');

    const [items, total] = await queryBuilder.getManyAndCount();

    return { items, total, page, pageSize };
  }

  async findOne(id: number): Promise<OperationReport> {
    const report = await this.reportsRepository.findOne({ where: { id } });
    if (!report) {
      throw new NotFoundException(`报表ID ${id} 不存在`);
    }
    return report;
  }

  async getLatestReport(): Promise<OperationReport | null> {
    return this.reportsRepository.findOne({
      order: { createdAt: 'DESC' },
    });
  }

  async getSummary() {
    const totalUsers = await this.usersRepository.count();
    const totalContests = await this.contestsRepository.count();
    const totalProblems = await this.problemsRepository.count();
    const totalSubmissions = await this.submissionsRepository.count();
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const todaySubmissions = await this.submissionsRepository.count({
      where: { createdAt: Between(today, new Date()) },
    });

    return {
      totalUsers,
      totalContests,
      totalProblems,
      totalSubmissions,
      todaySubmissions,
    };
  }

  async getMonthlyReport(year?: number, month?: number) {
    const now = new Date();
    const targetYear = year ?? now.getFullYear();
    const targetMonth = month ?? (now.getMonth() === 0 ? 12 : now.getMonth());

    const realYear = targetMonth === 12 ? targetYear - 1 : targetYear;
    const realMonthIndex = targetMonth === 12 ? 11 : targetMonth - 1;

    const periodStart = new Date(realYear, realMonthIndex, 1);
    const periodEnd = new Date(realYear, realMonthIndex + 1, 0, 23, 59, 59, 999);

    const existing = await this.reportsRepository.findOne({
      where: {
        period: ReportPeriod.MONTHLY,
        periodStart: periodStart as any,
        periodEnd: periodEnd as any,
      },
    });

    if (existing) {
      return existing;
    }

    return this.generateReport(ReportPeriod.MONTHLY, periodStart, periodEnd, false);
  }
}
