import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, Index, Unique } from 'typeorm';
import { ApiProperty } from '@nestjs/swagger';

export enum ReportPeriod {
  DAILY = 'daily',
  WEEKLY = 'weekly',
  MONTHLY = 'monthly',
}

@Entity('operation_reports')
@Unique(['period', 'periodStart', 'periodEnd'])
export class OperationReport {
  @ApiProperty({ description: '报表ID' })
  @PrimaryGeneratedColumn()
  id: number;

  @ApiProperty({ description: '报表周期类型', enum: ReportPeriod })
  @Column({
    name: 'period',
    type: 'enum',
    enum: ReportPeriod,
    default: ReportPeriod.MONTHLY,
  })
  period: ReportPeriod;

  @ApiProperty({ description: '周期开始时间' })
  @Column({ name: 'period_start', type: 'date' })
  @Index()
  periodStart: Date;

  @ApiProperty({ description: '周期结束时间' })
  @Column({ name: 'period_end', type: 'date' })
  @Index()
  periodEnd: Date;

  @ApiProperty({ description: '报表标题' })
  @Column({ name: 'title', length: 200 })
  title: string;

  @ApiProperty({ description: '新增用户数' })
  @Column({ name: 'new_users', type: 'int', default: 0 })
  newUsers: number;

  @ApiProperty({ description: '活跃用户数' })
  @Column({ name: 'active_users', type: 'int', default: 0 })
  activeUsers: number;

  @ApiProperty({ description: '总用户数' })
  @Column({ name: 'total_users', type: 'int', default: 0 })
  totalUsers: number;

  @ApiProperty({ description: '新增竞赛数' })
  @Column({ name: 'new_contests', type: 'int', default: 0 })
  newContests: number;

  @ApiProperty({ description: '进行中竞赛数' })
  @Column({ name: 'ongoing_contests', type: 'int', default: 0 })
  ongoingContests: number;

  @ApiProperty({ description: '总竞赛数' })
  @Column({ name: 'total_contests', type: 'int', default: 0 })
  totalContests: number;

  @ApiProperty({ description: '新增题目数' })
  @Column({ name: 'new_problems', type: 'int', default: 0 })
  newProblems: number;

  @ApiProperty({ description: '总题目数' })
  @Column({ name: 'total_problems', type: 'int', default: 0 })
  totalProblems: number;

  @ApiProperty({ description: '新增提交数' })
  @Column({ name: 'new_submissions', type: 'int', default: 0 })
  newSubmissions: number;

  @ApiProperty({ description: '总提交数' })
  @Column({ name: 'total_submissions', type: 'int', default: 0 })
  totalSubmissions: number;

  @ApiProperty({ description: 'AC提交数' })
  @Column({ name: 'accepted_submissions', type: 'int', default: 0 })
  acceptedSubmissions: number;

  @ApiProperty({ description: '平均通过率（%）' })
  @Column({ name: 'average_acceptance_rate', type: 'float', default: 0 })
  averageAcceptanceRate: number;

  @ApiProperty({ description: '报名人数' })
  @Column({ name: 'registrations', type: 'int', default: 0 })
  registrations: number;

  @ApiProperty({ description: '反作弊检测异常数' })
  @Column({ name: 'anti_cheat_alerts', type: 'int', default: 0 })
  antiCheatAlerts: number;

  @ApiProperty({ description: '生成的证书数' })
  @Column({ name: 'certificates_issued', type: 'int', default: 0 })
  certificatesIssued: number;

  @ApiProperty({ description: '统计数据明细（JSON）' })
  @Column({ name: 'details', type: 'json', nullable: true })
  details: any;

  @ApiProperty({ description: '备注' })
  @Column({ name: 'remark', type: 'text', nullable: true })
  remark: string;

  @ApiProperty({ description: '是否自动生成' })
  @Column({ name: 'is_auto_generated', type: 'boolean', default: true })
  isAutoGenerated: boolean;

  @ApiProperty({ description: '创建时间' })
  @CreateDateColumn({ name: 'created_at' })
  @Index()
  createdAt: Date;
}
